services:
  nginx:
    container_name: nginx
    build: nginx
    ports:
      - 8080:80
  mongo:
    container_name: mongo
    restart: always
    image: mongo:latest
    volumes:
      - ./data:/data/db
    expose:
      - 27017
  debian:
    container_name: ftp
    image: debian:latest